name             'ruby-env'
maintainer       'Ryutaro YOSHIBAE'
maintainer_email 'ryuzee@gmail.com'
license          'MIT'
description      'Installs/Configures ruby-env'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'yum', '>= 3.0'
depends          'build-essential'
depends          'git'
depends          'nginx'
